on:
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: duty-machine/duty-machine-action@master
        env:
          TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          REPOSITORY: shenweiyan/Issues
          EVENT: ${{ toJson(github.event) }}
